name: Build Android APK

on:
  push:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Set up JDK 17
      uses: actions/setup-java@v4
      with:
        java-version: '17'
        distribution: 'temurin'

    - name: Set up Flutter
      uses: subosito/flutter-action@v2
      with:
        channel: 'stable'

    - name: Get dependencies
      run: flutter pub get

    - name: Build APK
      run: flutter build apk --debug

    - name: Upload to transfer.sh & Generate QR
      run: |
        echo "=== ССЫЛКА НА СКАЧИВАНИЕ И QR-КОД ==="
        URL=$(curl --upload-file build/app/outputs/flutter-apk/app-debug.apk https://transfer.sh)
        echo "Ссылка для телефона: $URL"
        curl -s "https://qrenco.de"
